server:
  port: 8087

spring:
  application:
    name: statistical-service

  datasource:
    url: jdbc:h2:mem:db_statistical;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

grpc:
  server:
    port: 9087
  client:
    citizen-service:
      address: discovery:///civil-pro-citizen
      enable-keep-alive: true
      negotiation-type: plaintext
    household-service:
      address: discovery:///civil-pro-household
      enable-keep-alive: true
      negotiation-type: plaintext
    fluctuation-service:
      address: discovery:///civil-pro-fluctuations
      enable-keep-alive: true
      negotiation-type: plaintext

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
