server:
  port: 8089

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:h2:mem:db_payment;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

grpc:
  server:
    port: 9089
  client:
    auth-service:
      address: discovery:///civil-pro-auth
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

civil-pro:
  kafka:
    topics:
      payment-events: payment.events
