spring.application.name=citizen
spring.config.import=optional:configserver:http://localhost:8888

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=citizen-service

spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

civil-pro.kafka.topics.citizen-created=citizen.created
civil-pro.kafka.topics.citizen-updated=citizen.updated
civil-pro.kafka.topics.citizen-deceased=citizen.deceased
civil-pro.kafka.topics.change-log-created=citizen.change-log-created
civil-pro.kafka.topics.relationship-created=citizen.relationship-created